import { Service } from "@/types";

export const services: Service[] = [
  {
    id: "1",
    slug: "custom-websites",
    title: "Custom Websites",
    shortDescription: "High-performance, conversion-optimized websites tailored to your brand.",
    longDescription: "We build premium websites that aren't just digital brochures but powerful business tools. Our focus is on performance, SEO, and user experience.",
    icon: "Globe",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800",
    benefits: ["Faster load times", "Better SEO rankings", "Higher conversion rates"],
    features: ["Responsive design", "CMS integration", "Custom animations"],
    process: [
      { title: "Discovery", description: "Understanding your goals and audience." },
      { title: "Design", description: "Crafting a unique visual identity." }
    ],
    pricingFrom: "Starting from ₹49,999",
    faq: [],
    cta: "Start Your Website Project"
  },
  {
    id: "2",
    slug: "clinic-management-systems",
    title: "Clinic Management Systems",
    shortDescription: "Streamline your practice with custom appointment and patient management.",
    longDescription: "End-to-end solutions for dental and dermatology clinics to manage appointments, patient records, and billing.",
    icon: "Stethoscope",
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&q=80&w=800",
    benefits: ["Reduce no-shows", "Paperless records", "Efficient scheduling"],
    features: ["Appointment booking", "Patient portal", "Automated reminders"],
    process: [],
    pricingFrom: "Starting from ₹1,49,999",
    faq: [],
    cta: "Modernize Your Clinic"
  },
  {
    id: "3",
    slug: "restaurant-management-software",
    title: "Restaurant Management Software",
    shortDescription: "POS, inventory, and table management for modern eateries.",
    longDescription: "Complete software suite for restaurants, cafes, and bars to handle orders, inventory, and customer loyalty.",
    icon: "Utensils",
    image: "https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&q=80&w=800",
    benefits: ["Optimized operations", "Real-time inventory tracking", "Enhanced customer loyalty"],
    features: ["Digital Menu", "POS Integration", "Kitchen Display System"],
    process: [],
    pricingFrom: "Starting from ₹99,999",
    faq: [],
    cta: "Boost Your Restaurant"
  },
  {
    id: "4",
    slug: "crm-development",
    title: "CRM Development",
    shortDescription: "Custom CRM systems to manage your customer relationships effectively.",
    longDescription: "Tailor-made CRM solutions that fit your specific business workflows, helping you close more deals.",
    icon: "Users",
    image: "https://images.unsplash.com/photo-1551288049-bbbda536ad0a?auto=format&fit=crop&q=80&w=800",
    benefits: ["Centralized data", "Improved sales tracking", "Better customer support"],
    features: ["Lead management", "Pipeline tracking", "Email automation"],
    process: [],
    pricingFrom: "Starting from ₹1,99,999",
    faq: [],
    cta: "Build Your CRM"
  },
  {
    id: "5",
    slug: "appointment-booking-systems",
    title: "Appointment Booking Systems",
    shortDescription: "Simple and powerful booking systems for service-based businesses.",
    longDescription: "Allow your clients to book services online 24/7 with a seamless scheduling experience.",
    icon: "Calendar",
    image: "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&q=80&w=800",
    benefits: ["24/7 booking", "Reduced admin work", "Better calendar management"],
    features: ["Staff scheduling", "Service categories", "Online payments"],
    process: [],
    pricingFrom: "Starting from ₹39,999",
    faq: [],
    cta: "Get Booking System"
  },
  {
    id: "6",
    slug: "ai-integrations",
    title: "AI Integrations",
    shortDescription: "Incorporate AI into your business to automate tasks and gain insights.",
    longDescription: "Leverage LLMs and custom AI models to enhance your products and internal processes.",
    icon: "Brain",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=800",
    benefits: ["Increased efficiency", "Automated support", "Data-driven decisions"],
    features: ["Chatbots", "Content generation", "Predictive analytics"],
    process: [],
    pricingFrom: "Starting from ₹79,999",
    faq: [],
    cta: "Integrate AI"
  },
  {
    id: "7",
    slug: "seo-optimization",
    title: "SEO Optimization",
    shortDescription: "Get found by your local customers on Google.",
    longDescription: "Comprehensive SEO strategies focusing on local search to drive traffic to your clinic or restaurant.",
    icon: "Search",
    image: "https://images.unsplash.com/photo-1562577353-f5d0d04c3e7b?auto=format&fit=crop&q=80&w=800",
    benefits: ["Higher visibility", "Organic traffic", "Local dominance"],
    features: ["Keyword research", "On-page SEO", "Local SEO / GMB"],
    process: [],
    pricingFrom: "Starting from ₹24,999/mo",
    faq: [],
    cta: "Rank Higher Now"
  },
  {
    id: "8",
    slug: "automation-solutions",
    title: "Automation Solutions",
    shortDescription: "Connect your apps and automate repetitive workflows.",
    longDescription: "Save hours of manual work by automating data transfer and communication between your business tools.",
    icon: "Zap",
    image: "https://images.unsplash.com/photo-1518433278981-167daff96261?auto=format&fit=crop&q=80&w=800",
    benefits: ["Save time", "Eliminate errors", "Scale faster"],
    features: ["Zapier/Make integration", "Custom scripts", "Workflow design"],
    process: [],
    pricingFrom: "Starting from ₹49,999",
    faq: [],
    cta: "Automate My Business"
  },
  {
    id: "9",
    slug: "dashboard-development",
    title: "Dashboard Development",
    shortDescription: "Visualize your business data for better decision making.",
    longDescription: "Custom dashboards that pull data from various sources to give you a clear view of your business health.",
    icon: "LayoutDashboard",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800",
    benefits: ["Data clarity", "Real-time monitoring", "Informed decisions"],
    features: ["Chart integrations", "Multi-source data", "Mobile friendly"],
    process: [],
    pricingFrom: "Starting from ₹89,999",
    faq: [],
    cta: "Visualize Your Data"
  },
  {
    id: "10",
    slug: "mobile-apps",
    title: "Mobile Apps",
    shortDescription: "Cross-platform mobile applications for iOS and Android.",
    longDescription: "Premium mobile experiences for your customers, from loyalty apps to complex business tools.",
    icon: "Smartphone",
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&q=80&w=800",
    benefits: ["Direct engagement", "Brand presence", "Offline access"],
    features: ["React Native / Flutter", "Push notifications", "App Store deployment"],
    process: [],
    pricingFrom: "Starting from ₹2,99,999",
    faq: [],
    cta: "Build Your App"
  }
];
